version: "3.8"

networks:
  app-tier:
    driver: bridge
services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3002:3002"
    environment:
      PRODUCT_SERVICE_URL: http://product-service:4002
      HOME_SERVICE_URL: http://home-service:4001
      CART_SERVICE_URL: http://cart-service:4003
      KAFKA_URL: kafka:9092
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    depends_on:
      - product-service
      - home-service
      - kafka
    networks:
      - app-tier

  home-service:
    build: ./home-service
    container_name: home-service
    ports:
      - "4001:4001"
    environment:
      - DB_NAME=kidsgamingzone
      - DB_USER=root
      - DB_PASSWORD=Yogi@1234
      - DB_HOST=host.docker.internal
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - KAFKA_URL=kafka:9092
    volumes:
      - ./home-service:/app
      - /app/node_modules
    depends_on:
      - kafka
      - redis
    networks:
      - app-tier

  cart-service:
    build: ./cart-service
    container_name: cart-service
    ports:
      - "4003:4003"
    environment:
      - DB_NAME=kidsgamingzone
      - DB_USER=root
      - DB_PASSWORD=Yogi@1234
      - DB_HOST=host.docker.internal
      - KAFKA_URL=kafka:9092
      - WEB_SOCKET_URL=http://api-gateway:3002
    volumes:
      - ./cart-service:/app
      - /app/node_modules
    depends_on:
      - kafka
      - redis
    networks:
      - app-tier
  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "4002:4002"
    environment:
      - DB_NAME=kidsgamingzone
      - DB_USER=root
      - DB_PASSWORD=Yogi@1234
      - DB_HOST=host.docker.internal
      - KAFKA_URL=kafka:9092
    volumes:
      - ./product-service:/app
      - /app/node_modules
    depends_on:
      - kafka
    networks:
      - app-tier
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-tier
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" # Important: auto-create topics
    volumes:
      - kafka_data:/bitnami/kafka
    depends_on:
      - zookeeper
    networks:
      - app-tier

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - app-tier
volumes:
  kafka_data:
